DOCUMENT = clan

pdf:
	texi2pdf $(DOCUMENT).texi

clean:
	rm -f $(DOCUMENT).aux $(DOCUMENT).cp $(DOCUMENT).fn $(DOCUMENT).ky \
	$(DOCUMENT).log $(DOCUMENT).pg $(DOCUMENT).toc \
	$(DOCUMENT).tp $(DOCUMENT).vr
